import React, { FC, ReactNode, useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import LoginButton from '../components/LoginButton';
import { useSession, signIn, signOut, getSession } from 'next-auth/react';
import { RippleMultiLoader } from '../components/Loaders';
import Header from '../components/Header';
import { BASE } from '../utils/appUtil';

const inter = Inter({ subsets: ['latin'] });

const Home: FC<ReactNode> = () => {
  const { data: session } = useSession({ required: false });

  useEffect(() => {
    if (session === null) {
      signIn();
    }
  }, [session]);

  if (session == undefined) return <RippleMultiLoader />;

  return (
    <>
      <Head>
        <title>Chatts App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Header />
        <LoginButton />
        <div className="channels__container">
          <h3>Select from an existing channels</h3>
          <div></div>
        </div>
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps = async (context: any) => {
  const { req } = context;
  const session = await getSession({ req });

  if (!session?.user?.email) return { props: {} };

  const res = await fetch(
    `${BASE}/channel/user-channels/${session.user.email}`
  );
  const channels = await res.json();
  console.log({ channels });
  return {
    props: {},
  };
};
